### ISSUE TITLE
Support for wayland

### ISSUE THREAD

**Issue by omarabid** [zpm-zsh/clipboard#6]
This doesn't support wayland/sway, right? Any plans to do that?

**Comment by grigorii-horos** [comment]
@omarabid I think xclip works under wayland via xwayland, so you can try to install `xclip`

**Comment by grigorii-horos** [comment]
@omarabid Or this does'n work?

**Comment by omarabid** [comment]
@grigorii-horos I'm not using xwayland because of an issue with my Graphic card (6700xt). Wayland has wl-copy. If you are open to integrate it, I can make a PR for it.

**Comment by grigorii-horos** [comment]
@omarabid You are welcome! Make a pr and I will merge it. But will be better to add something like wl-paste too

**Comment by grigorii-horos** [comment]
Done!
