### ISSUE TITLE
Parse error in clip, pbcopy, and pbpaste functions

### ISSUE THREAD

**Issue by edericsson** [zpm-zsh/clipboard#7]
Hi,
After updating to the latest version of clip, I'm getting parse errors for the clip, pbcopy, and pbpaste functions. As far as I can tell, this is due to an unclosed if block added in the latest commit.

> zsh ./functions/clip
> clip:30: parse error near `\n'
> cat ./functions/clip
> if [[ ! -t 0 ]]; then
>   if (( $+commands[xclip] )); then
>     xclip -selection clipboard -out
>   if (( $+commands[xsel] )); then
>     xsel -b
>   elif [[ "$OSTYPE" == darwin* ]]; then
>     command pbpaste
> ...

> cat ./functions/pbcopy
> #!/usr/bin/env zsh
> 
> if (( $+commands[xclip] )); then
>   xclip -selection clipboard -in
> if (( $+commands[xsel] )); then
>   xsel -b
> elif [[ "$OSTYPE" == darwin* ]]; then
> ...

**Comment by grigorii-horos** [comment]
@edericsson Fixed. Thanks for issue!

**Comment by edericsson** [comment]
I only copied the code from clip and pbcopy, but the issue is in pbpaste as well :P

**Comment by grigorii-horos** [comment]
@edericsson Fixed!
