### ISSUE TITLE
macOS 11.3.1 - zpm-zsh install - `clip:30: parse error near `\n'`

### ISSUE THREAD

**Issue by tal** [zpm-zsh/clipboard#8]
When I try and run any of the commands in this plugin I get the below error:
system: macOS 11.3.1
version: `0f562f8ffab1c70942d5588c652adf21110e05a2`

```
clip:30: parse error near `\n'
```

**Comment by grigorii-horos** [comment]
@tal Can you update this plugn?

**Comment by tobias-fyi** [comment]
I also received this error when trying to use `clip` on macOS 11.4, plugin installed via oh-my-zsh.
