### ISSUE TITLE
Inverted copy/paste in clip

### ISSUE THREAD

**Issue by victor-gp** [zpm-zsh/clipboard#9]
Hi @grigorii-horos,

Is it possible that copy and paste are in the wrong if branch of clip()?

I've been adapting that logic into my setup but I got errors. It makes sense: if stdin is not a terminal (so a pipe) then we should copy, otherwise we should paste.

Actually, it seems that was the behavior until [this commit](https://github.com/zpm-zsh/clipboard/commit/6f44d9eed6af79a02c77bb4997e3036b03fde03c#diff-6de8e7d1492b96491c72fd9408536a1eb4f3ef65a04c32e921ac2c327156d25c).

Aside from that, thanks for the plugin! clip() is super handy.

**Comment by edericsson** [comment]
I've submitted a pull request with a fix

**Comment by grigorii-horos** [comment]
Hey @edericsson . Thanks for pr!
